### ISSUE TITLE
Error using plugin-ts-standard-pkg, with workspaces + TSX

### ISSUE THREAD

**Issue by travomic** [pikapkg/pack#10]
I've create a minimal use-case example repository to demonstrate the issue I am attempting to use at: https://github.com/travomic/pika-tsx-monorepo

After installing the dependencies with `yarn` at the root of the monorepo, it definitely adds the `/node_modules/csstype` package.  But when trying to run the example tsx-component package build, it errors out with:
```
[3/5] Running @pika/plugin-ts-standard-pkg...
Error: Command failed: /Users/trave/Repos/pika-tsx-monorepo/packages/tsx-component/node_modules/.bin/tsc --outDir /Users/trave/Repos/pika-tsx-monorepo/packages/tsx-component/pkg/dist-src/ -d --declarationDir /Users/trave/Repos/pika-tsx-monorepo/packages/tsx-component/pkg/dist-types/ --declarationMap false --target es2018 --module esnext

../../node_modules/@types/react/index.d.ts(29,22): error TS2307: Cannot find module 'csstype'.

    at makeError (/Users/trave/Repos/pika-tsx-monorepo/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/Users/trave/Repos/pika-tsx-monorepo/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by FredKSchott** [comment]
Thanks for creating the use-case repo, this isn't something I've tried Pack with yet.

I'm travelling this weekend but will take a look into this early next week.

**Comment by FredKSchott** [comment]
wow I have no idea what to make of this, but I think it's just a TypeScript bug. I can reproduce outside of a monorepo, and just with a normal npm install. For some reason `@types/react` can't resolve that one dep. If you rewrite it to '../../csstype' it still can't resolve it. If you rewrite it to '../../csstype/index' it finally works and builds successfully. 

unrelated: you'll want to set "jsx" in your tsconfig to something besides `"preserve"`, since JSX is mainly dev-only and shouldn't be published directly to the registry (or at least, not in the `dist-src/` ES2018 distribution).
