### ISSUE TITLE
Avoid directly importing private files inside external packages.

### ISSUE THREAD

**Issue by beeman** [pikapkg/pack#12]
When building a project that uses `import { map } from rxjs/operators` this message gets triggered:

```
⚠️  [2:0] "rxjs/operators": Avoid directly importing private files inside external packages.
```

However, in case of RxJS this is the way of using it. Maybe `rxjs/*` can be whitelisted?

**Comment by FredKSchott** [comment]
Yea, I think this warning may be too opinionated :). If a package documents that this is how their package works, our answer shouldn't be "too bad that's not allowed". Curious what other people think here as well.

If anyone wants to take a stab at removing this from https://github.com/pikapkg/standard-pkg feel free, otherwise i'll take a look early next week

**Comment by FredKSchott** [comment]
Removed here: https://github.com/pikapkg/standard-pkg/commit/66a119f280130d721b923a25a42ad4dfee8eef7e
