### ISSUE TITLE
Expected file locations

### ISSUE THREAD

**Issue by matthewp** [pikapkg/pack#21]
I keep getting this one:

```js
Error: @pika/pack expects a standard package format, where the package entrypoint must live at "src/index".
```

I find this one a little confusing, why is it not respecting the package.json `main` as the entry point?

The main reason I ran into this is because I was trying to create a gist for another issue and gists don't allow folders.  Still seems non-optimal

**Comment by FredKSchott** [comment]
Yup, that's an opinionated choice that a lot of our build plugins rely on. Just put your file where we always expect them, and then no configuration needed. It also:
- Allows all build plugins (including 3rd party) to assume a standard location of files to read from / write to
- Guarantees that all different distributions (`dist-node/index.js`, `dist-web/index.js`) will be able to reference the same shared assets (`assets/foo.bar`) without rewriting imports (`"../assets/foo.bar"`)

Not saying it's perfect, but it was an intentional limitation.

**Comment by ryaninvents** [comment]
@matthewp quick hack fix in `package.json` might help:

```json
{
  "scripts": {
    "postinstall": "mkdir src && cp *.js src/"
  }
}
```

Then just make sure that `.gitignore` contains the `src/` directory so it does not get pushed back to Gist. Not sure how it's set up on their end, but GitHub might reject the push.

**Comment by FredKSchott** [comment]
We actually have undocumented support for running bare scripts inside your pipeline...

```
"pipeline": [
  "cp *.js src/",
   ["@pika/plugin-standard-pkg"]
],
```
Just use a string instead of an array.

One big feature I'd like to add is an in-memory File System for the build pipeline, so that each plugin doesn't have to read/write to disk to communicate with other plugins, and then it all gets written to disk at the end. That would also allow a "prepare" type plugin to collect your files for you before running `@pika/plugin-standard-pkg`, without having to write to disk.

**Comment by PaulSearcy** [comment]
Is there any chance of adding a configuration option to respect 'main' in package or add a specific or multiple 'entry-point' property to pikapkg in the future?

Due to the nature and constraints of a project (.Net Core MVC ) and trying to encapsulate .css and .js with their components ( views ). I'm running a webpack configuration with multiple entry-points and aliases. 

In my case I can't just cp ~ Copy-Item, due to module references in JS files either containing alias characters ( '~' -> wwwroot ) or full path in dev/test for Intellisense completion (../../wwwroot/utilities/utilities.js)

This might be out of scope or not a priority at the moment for this project.

 Irregardless I definitely see the value of this project, having wired up .mjs modules  with HTTP2  on server by hand as a POC in the past! :thumbsup:

**Comment by FredKSchott** [comment]
I'm not opposed to the idea of a package exporting different entrypoints, but the way this happens today is too messy for a tool like @pika/pack to support well.

- With a package name, you can point to the package, and let the bundler/installer decide which distribution is right for your envorinment.
- With a package name + file path, you've hardcoded the distribution into your package/app/project.

In my mind this would have to be solved in the rest of the ecosystem (Node.js, npm, bundlers), but I'm 100% behind any efforts to do so. (I'm also 110% behind anyone who wants to tell me that I'm wrong on this and why :)

Supporting a non-`src/index.js` entrypoint is more in our control, but would need to be done well/carefully. Right now all plugins are able to assume that "index.js" is the main package file inside of each distribution, so it gives them some stability & confidence in working with user code. I'd love to see a non-official plugin experiment with this more.

**Comment by gilbert** [comment]
> With a package name + file path, you've hardcoded the distribution into your package/app/project

Can you explain what you mean by this? Just trying to understand.

**Comment by FredKSchott** [comment]
* `import * as foobar from 'foobar/index.es5.js'` -  forces everyone to use the es5 version of foobar, even if they're on a more modern environment.
* `import * as foobar from 'foobar/index.browser.js'` -  forces everyone to use the browser version of foobar, even if they're on Node.js (future).
