### ISSUE TITLE
Cannot find module @pika/types

### ISSUE THREAD

**Issue by gilbert** [pikapkg/pack#33]
Just a quick report, after installing `@pika/plugin-ts-standard-pkg` and only having that in my pipeline, I had to manually install `@pika/types` to remove the error. Worked fine afterwards.

**Comment by stramel** [comment]
Possibly related to #23

**Comment by FredKSchott** [comment]
Why. Won't. This. Issue. Die!!! @pika/types was marked as a dev dependency instead of a production one. I swear I already fixed this once before...

Commit here: https://github.com/pikapkg/builders/commit/19cb1fabc1dca5b376e7c50e64e845a3305ba3f4
Went out in: v0.3.14 of the builder package, just now

Updating/reinstalling the dependency should fix the issue. Thanks for filing & reporting!

**Comment by aendra-rininsland** [comment]
This just happened to me using `npx @pika/pack`; installing it as a dependency to the project seems to have fixed it?
