### ISSUE TITLE
Multiple npm packages within a single repo

### ISSUE THREAD

**Issue by backspaces** [pikapkg/pack#40]
I believe it currently is not possible to use pika/pack to create multiple npm packages from a single repo. I say that because it needs a single package.json.

- Is that right? If not, this is a documentation request to show how.
- If so: a feature request: multiple npm packages within a single git/github repo.

Thanks!

**Comment by FredKSchott** [comment]
The README has a short section on Lerna support. Are you requesting something different, or should that title be expanded to be more clear? (ex: "Lerna / Monorepo Support")

**Comment by backspaces** [comment]
Hi, thanks for getting back. I did notice the use of lerna in the repo, but I didn't see use of pika/pack in the build, only lerna commands.

I basically want to not use lerna at all, but just pika/pack for multiple npm packages in a single repo.  I've looked at lerna and it seemed complex, requiring a package.json for each npm package.

So this issue is basically "can I have pika/pack build multiple npm packages in a single repo?". If not, that's OK. And if there is some sort of synergy between the two, maybe a pointer to where they are used together that I missed.

Hope this makes sense!

**Comment by thibthib** [comment]
👋  I have kind of the same need, where I would want to be able to install and configure `@pika/pack` once, to build several packages – in my case they all have their own `package.json`.

**Comment by FredKSchott** [comment]
@backspaces thanks, that makes more sense. I don't think that's in scope just yet, although I could certainly see it in the future. 
@thibthib this would be possible with Lerna + @pika/pack. See: https://github.com/pikapkg/builders

**Comment by thibthib** [comment]
@FredKSchott I actually don't want to duplicate my build configuration in each an every package, like it's done in the builders. I want something like create-react-app, where I put my build configuration and tools in one place, and then I can use it directly in all my packages.

**Comment by tunnckoCore** [comment]
@FredKSchott to clarify what I'm understanding they want. And I agree. There's no need in every package to have scripts with `build` and `@pika/pack` and its plugins to be inside the devDependencies of every package - there should only have devDependencies specific to the package. It's cleaner that way I'm doing it that way too in my monorepo setup https://github.com/tunnckoCore/monorepo. 

From all that I'm seeing 2 things:

1. Feature (with the assumption every package has package.json of course): be possible to run `pika-pack` from the root and build all of the packages in one go. I'll explain below how this can be achieved with zero-to-few lines of code and single minimal dependency (which has just `execa` as a dependency which you already have here).
2. Problem / Cause:  Both @yarnpkg and @npm does not understand monorepos well (even with `lerna exec` won't work). If you are in the package and don't have the `@pika/pack` installed it will throw - that's probably why you did it that way. So the tool must understand where it is invoked. And that's easy:

```js
const cwd = process.cwd()

// double path.dirname calls
const dirname = path.basename(path.dirname(path.dirname(cwd)))

// glob-base package examples
console.log(globBase('packages/@tunnckocore/*')
{ base: 'packages/@tunnckocore', isGlob: true, glob: '*' }

console.log(globBase('packages/*')
{ base: 'packages', isGlob: true, glob: '*' }

// get the `lerna.json` packages array or `package.json` field `workspaces` 

const isInPackageCwd = packages.map(x => globBase(x).base).includes(dirname)
const isInMonorepoRoot = !isInPackageCwd
```
_(doh i'm doing that for n-th time, i might extract it already ;d)_


- Support `pika-pack build [package-name]` from the root, (i think that's what they want in that issue).
- Support building all packages in sequence/parallel.


**But.** More easier thing would be to replace `@pika/pack` with [@tunnckocore/scripts (i can rename it)](https://github.com/tunnckoCoreLabs/scripts), the above-mentioned thing, as devDependency to each package. _It's not like react-scripts or etc, it's a shell/command executor which understands monorepos, in bonus it just happens to work like a tasks runner with hooks and shareable configs too_. 

Then in the `scripts.build` you can just prepend the `pika-pack build` with `yarn scripts`, so `yarn scripts pika-pack build` or just `scripts pika-pack build`. So, you will only have `@pika/pack` on the root and will not throw when you run `lerna run build` for example, because it finds the bin from the root. So you can see, why the above snippet with `isMonorepoSetup` is needed.

---

Aaaaanyway. That got too long, but hope it helps - i'm in that business for a long time and have tons of similar low-level stuff for a reason 💃 Btw, not sure how your plugin system works but also might be interested in [resolve-plugins-sync](https://github.com/tunnckocore/resolve-plugins-sync "plugins/transforms/configs resolver like seen on babel/browserify/eslint and etc") - _plugins/transforms/configs resolver like seen on babel/browserify/eslint and etc_. 

Also, review my monorepo for inspirations and working configs of jest, bundling, eslint and etc. I'm going to host as much as possible of my 400 packages on a single independently-versioned monorepo setup - quite crazy and tricky.

---

Another interesting work is [hela](https://github.com/tunnckoCore/hela) (also the `v3-major` branch, or from the opened issue)

**Comment by tunnckoCore** [comment]
One more needed feature in the branch of "monorepo mind": Allow if it is in monorepo setup and called with a `--cwd` (so, from some of the packages) to detect if there is `@pika/pack` field on that package package.json, otherwise fallpack to the piple from the root of the repo.

Later, I'll show link with crazy working monorepo: https://github.com/tunnckoCoreHQ/opensource stay tuned. It has only the pika config on each package package.json - and this may make sense, for example if you want different pipelines for different packages.
