### ISSUE TITLE
Unable to exclude snapshots from @pika/plugin-standard-pkg

### ISSUE THREAD

**Issue by tutts** [pikapkg/pack#42]
Hello,

I received this error while publishing my package:

![image](https://user-images.githubusercontent.com/7454558/55010164-a5d2d280-4fdb-11e9-842f-20e4138adec5.png)

however no matter the configuration, I couldn't get the glob to exclude it:

```
"@pika/pack": {
    "pipeline": [
      [
        "@pika/plugin-standard-pkg",
        {
          "exclude": [
            "*.spec.js",
            "*.js.snap"
          ]
        }
      ],
      [
        "@pika/plugin-build-node"
      ],
      [
        "@pika/plugin-build-web"
      ],
      [
        "@pika/plugin-build-types"
      ]
    ]
```

**Comment by FredKSchott** [comment]
Interesting. I wonder if the globbing package that we use matches against the full path, so that it would match `foo.spec.js` but not `foo/bar.spec.js`.

Can you try adding one of these to `exclude` to see if any of them do the trick?
-  `__snapshots__/` 
-  `__snapshots__/**`
-  `__snapshots__/**/*`  
-  `**/*.spec.js`
- `**/*.js.snap`

**Comment by tutts** [comment]
> I wonder if the globbing package that we use matches against the full path, so that it would match foo.spec.js but not foo/bar.spec.js.

I suspect you're right, results below...

```
- __snapshots__/ 🔴 
- __snapshots__/** ✅ 
- __snapshots__/**/* ✅ 
- **/*.spec.js 🔴 
- **/*.js.snap ✅ 
```

thanks for the help!

**Comment by FredKSchott** [comment]
np! For any future readers, we use this: https://www.npmjs.com/package/glob
