### ISSUE TITLE
@pika/build and @pika/web interoperability using esnext entrypoints only

### ISSUE THREAD

**Issue by chrisware** [pikapkg/pack#56]
I'm trying to use a pure ES2018 module I've created directly in a browser environment. The module package has been built using `@pika/plugin-standard-pkg` plugin and I'm trying to bundle it with @pika/web in my web project.

First I build the module package using `@pika/plugin-standard-pkg`. This creates `pkg/dist-src` with an "esnext" entrypoint in `pkg/package.json` as per the @pika/pack documentation.

However in my web project, when I try and install the dependency using `npx @pika/web` I get an error "`@pika/web installing... Error: You must supply options.input to rollup`". I know this is because the dependency doesn't export a "module" entrypoint in `package.json` as expected by @pika/web.

Note that I could (but do not want to) use the `@pika/plugin-build-web` build plugin (which does generate the "module" entry point).  This is because it compiles to an ESM distribution and that's not what I need.  I'm only targeting Chrome browser environment for this project, the ESM code ends up being 3x larger than the original module which just seems wasteful.

Is there a way to create and use my ES2018 module using this pipeline with only `@pika/plugin-standard-pkg`?

**Comment by FredKSchott** [comment]
Hey @chrisware, thanks for the message.

I've been talking with a few people about this, and I think you're right. `@pika/plugin-build-web`'s distribution target no longer makes sense to be as legacy as it is.  Consumers are compiling their dependencies now, and allowing "module" to always be the latest spec would be a huge win for performance and package size.

I still like the idea of being explicit about adding a "web" builder, since it signifies your intention a bit more explicitly. But I'm also willing to experiment a bit here, since the whole multiple distributions concept may not even make sense once Node releases ESM support.

**Comment by FredKSchott** [comment]
To answer your immediate question: you can specify specific entrypoints via configuration, to point to your `dist-src/index.js` build. See: https://github.com/pikapkg/web#packagejson-options

**Comment by chrisware** [comment]
Thanks @FredKSchott - however if I understood that right, then specifying "`mymodule/dist-src/index.js`" in "webDependencies" of package.json ends up building to `web_modules/mymodule/dist-src/`  which means I can't `import foo from  '/web_modules/mymodule/modulename.js'`  but rather have to `import foo from '/web_modules/mymodule/dist-src/index.js'` which doesn't feel right

**Comment by FredKSchott** [comment]
Agreed, this is a short term workaround until @pika/pack is updated to publish modern JS to the "module" entrypoint.

**Comment by FredKSchott** [comment]
This went out with v0.5.1 of the package builders back in July. Cheers!
