### ISSUE TITLE
[typescript] tsconfig.json [compilerOptions.target] should be "es2019", but found "8"

### ISSUE THREAD

**Issue by kripod** [pikapkg/pack#57]
The warning in the title is raised when using the following `tsconfig.json` file:

```json
{
  "compilerOptions": {
    "strict": true,
    "target": "esnext",
    "module": "esnext"
  }
}
```

I think that the arbitrary choice of `es2019` is not reasonable from a maintainability perspective, as the file mentioned above should be changed year by year without much benefit. On the other hand, recommending `esnext` would be a future-proof decision.

**Comment by FredKSchott** [comment]
That's actually intentional, we only want to target the latest spec in our published packages. Anything ESNext is considered experimental / not yet baked, meaning you could ship code to the ecosystem that:
1. doesn't end up matching the final syntax
2. consumers don't have the polyfills for.

Bumping a number once a year is a small price to pay, and it's an explicit commitment from the author that they have maintained and updated their library to the latest agreed on spec.

**Comment by vgpena** [comment]
Noting here that you may also have to upgrade TypeScript to make this work. My original version of TS was old enough that it didn't know that `es2019` was an option.
