### ISSUE TITLE
Discussion: Faster iteration development builds (watch command, etc.)

### ISSUE THREAD

**Issue by jvdsande** [pikapkg/pack#68]
Hi @pikapkg team!
First of all thanks for @pika/pack =)

I was wondering today if there is a way (or plans for adding a way) to set the pipeline differently according to the NODE_ENV environment variable.

My use-case for this is quite simple: 
I want to use `@pika/plugin-build-types` (or even `@pika/plugin-ts-standard-pkg`) when building for production, but wish I could fallback to using `@pika/plugin-standard-pkg` alone while in development, since the `tsc` step is quite slow.

So doing:
```NODE_ENV=development pack build```

Would trigger only `@pika/plugin-standard-pkg`, while

```pack build``` or ```NODE_ENV=production pack build``` 

Would use `@pika/plugin-ts-standard-pkg`

Is that possible at all?

On a side-note, a `pack watch` command would be awesome !

**Comment by xlxAciDxlx** [comment]
Any word or further discussion on a `watch` argument or mode? I quickly fell in love with pika because, in general, I don't have to jump through hoops and huge configurations to have my project public-ready (or even just browser-ready). However, the biggest downside right now is that the build folder gets completely nuked on a build, which breaks cases like a Webpack import (module X not found because the folder it expected to be able to read from is gone).

### Possible Solutions
- Option to _not_ delete the build folder/files on build
  - Perhaps a CLI option
  - Perhaps a key in `package.json`, i.e `keepDir` or `nukeBuildDir`
- Watch mode that watches files and triggers builds on it's own combined with something similar to the above suggestion

I'm more than willing to try to contribute in any way that I can, though unfortunately I haven't the slightest clue where to even start.

---

I currently work around the issue of not having a "watch" mode by using Gulp (gulp watch → file change → run build script in the changed package). It works, but unfortunately, with pika nuking the build folder it still breaks in other ways than I had to work around with using Gulp in the first place.

**Comment by jvdsande** [comment]
@xlxAciDxlx
Good suggestions.
The nuke dir system has also been getting in my way.

For now I've solved it by configuring pika to build in a temp dir, and adding an mv command to the end of my gulp flow to move override the actual destination. This way webpack&co stay happy.

This is definitely a hack though, a more official solution would be greatly appreciated
