### ISSUE TITLE
Issue resolving files in dist-web and dist-node

### ISSUE THREAD

**Issue by Jaredk3nt** [pikapkg/pack#7]
Hey trying out pika and ran into an issue after building importing in a web project. I get the error

```
./node_modules/fun-enums/dist-web/index.js
Module not found: Can't resolve './initializers' in '<full-path-redacted>/node_modules/fun-enums/dist-web'
```

when trying to import like this: `import { enums } from 'fun-enums';`.

Here is my pipeline:

```json
"@pika/pack": {
    "pipeline": [
      ["@pika/plugin-standard-pkg"],
      ["@pika/plugin-build-node"],
      ["@pika/plugin-build-web"]
    ]
  }
```

My project structure is:

```text
/src
  index.js
  inititalizers.js
/test
  enums.test.js
```

But when the package structure only has initializers.js under `dist-src`:

```text
/pkg
  /dist-node
    index.js
  /dist-src
    index.js
    initializers.js
  /dist-web
    index.js
  package.json
  README.md
```

Is there some other configuration that I need to get `initializers.js` to be built for web and node?

**Comment by FredKSchott** [comment]
Your `src/` directory needs to be ESM syntax (`import` instead of `require()`). The `@pika/plugin-standard-pkg` plugin should warn about using require() when you run the build pipeline, let me know if it isn't...

On a successful build, `dist-node` & `dist-web` are bundled into a single file, so `initializers.js` will already be included in that single-file `dist-node/index.js` & `dist-web/index.js` automatically. You can check the code itself to confirm that it's included correctly.

**Comment by imakou** [comment]
Same issue here.
My `CountDownButton.js` is not included in `dist-node/index.js` & `dist-web/index.js`

I also experiencing "Cannot resolve model" issue when I tried to import the npm pkg that I built by Pika/pack.

![image](https://user-images.githubusercontent.com/1507950/93414862-35bfa880-f870-11ea-948b-855910657146.png)
